function readFileAsText(file){
    return new Promise((resolve,reject)=>{
        const reader = new FileReader();
        reader.onload = ()=>resolve(reader.result);
        reader.onerror = ()=>reject(reader.error);
        reader.readAsText(file);
    });
}

function generateOffsetDcp(d1, d2, d3){
    // Minimal offset-style generator: include markers and simple merge.
    // TODO: replace with real offset algorithm if available.
    const parts = [d1||'', d2||'', d3||''];
    const header = `# Generated offset-style DCP\n# Generated by DCP-Tool (minimal)\n\n`;
    const body = parts.map((p,i)=>`--- DCP PART ${i+1} START ---\n${p}\n--- DCP PART ${i+1} END ---\n`).join('\n');
    return header + body;
}

function downloadText(filename, text){
    const blob = new Blob([text], {type: 'text/plain'});
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(()=>URL.revokeObjectURL(url), 5000);
}

document.addEventListener('DOMContentLoaded', ()=>{
    const file1 = document.getElementById('dcp-file-1');
    const file2 = document.getElementById('dcp-file-2');
    const file3 = document.getElementById('dcp-file-3');
    const name1 = document.getElementById('dcp-name-1');
    const name2 = document.getElementById('dcp-name-2');
    const name3 = document.getElementById('dcp-name-3');
    const btn = document.getElementById('generate-download');

    [file1,file2,file3].forEach((f, idx)=>{
        f.addEventListener('change', ()=>{
            const n = f.files && f.files[0] ? f.files[0].name : '尚未選擇檔案';
            if(idx===0) name1.textContent = n;
            if(idx===1) name2.textContent = n;
            if(idx===2) name3.textContent = n;
        });
    });

    btn.addEventListener('click', async ()=>{
        btn.disabled = true;
        btn.textContent = '正在產生...';
        try{
            const reads = [file1,file2,file3].map(f=> f.files && f.files[0] ? readFileAsText(f.files[0]) : Promise.resolve(''));
            const [t1,t2,t3] = await Promise.all(reads);
            const out = generateOffsetDcp(t1,t2,t3);
            const filename = 'offset-style.dcp';
            downloadText(filename, out);
        }catch(err){
            console.error('生成失敗', err);
            alert('產生失敗：' + (err && err.message ? err.message : String(err)));
        }finally{
            btn.disabled = false;
            btn.textContent = '產生並下載 offset-style DCP';
        }
    });
});
