export const CAMERA_PROFILE_MAGIC = 0x4352;
export const TIFF_MAGIC = 0x002A;

export const STRATEGY = {
    ADDITIVE: "additive",
    CHANNEL_RATIO: "channel_ratio",
    COPY_STYLE: "copy_style",
    GAIN_MAP: "gain_map",
    HSV_TABLE: "hsv_table",
    MATRIX: "matrix",
    MONOTONIC_LUT: "monotonic_lut",
    POSITIVE_RATIO: "positive_ratio",
    TONE_CURVE: "tone_curve",
    WHITE_POINT_XY: "white_point_xy",
};

export const TIFF_TYPES = {
    1: { name: "BYTE", size: 1, kind: "integer" },
    2: { name: "ASCII", size: 1, kind: "ascii" },
    3: { name: "SHORT", size: 2, kind: "integer" },
    4: { name: "LONG", size: 4, kind: "integer" },
    5: { name: "RATIONAL", size: 8, kind: "rational" },
    6: { name: "SBYTE", size: 1, kind: "integer" },
    7: { name: "UNDEFINED", size: 1, kind: "bytes" },
    8: { name: "SSHORT", size: 2, kind: "integer" },
    9: { name: "SLONG", size: 4, kind: "integer" },
    10: { name: "SRATIONAL", size: 8, kind: "rational" },
    11: { name: "FLOAT", size: 4, kind: "float" },
    12: { name: "DOUBLE", size: 8, kind: "float" },
};

export const TAG_NAME_BY_ID = new Map([
    [50706, "DNGVersion"],
    [50707, "DNGBackwardVersion"],
    [50708, "UniqueCameraModel"],
    [50709, "LocalizedCameraModel"],
    [50710, "CFAPlaneColor"],
    [50711, "CFALayout"],
    [50712, "LinearizationTable"],
    [50713, "BlackLevelRepeatDim"],
    [50714, "BlackLevel"],
    [50715, "BlackLevelDeltaH"],
    [50716, "BlackLevelDeltaV"],
    [50717, "WhiteLevel"],
    [50718, "DefaultScale"],
    [50719, "DefaultCropOrigin"],
    [50720, "DefaultCropSize"],
    [50721, "ColorMatrix1"],
    [50722, "ColorMatrix2"],
    [50723, "CameraCalibration1"],
    [50724, "CameraCalibration2"],
    [50725, "ReductionMatrix1"],
    [50726, "ReductionMatrix2"],
    [50727, "AnalogBalance"],
    [50728, "AsShotNeutral"],
    [50729, "AsShotWhiteXY"],
    [50730, "BaselineExposure"],
    [50731, "BaselineNoise"],
    [50732, "BaselineSharpness"],
    [50733, "BayerGreenSplit"],
    [50734, "LinearResponseLimit"],
    [50735, "CameraSerialNumber"],
    [50736, "LensInfo"],
    [50737, "ChromaBlurRadius"],
    [50738, "AntiAliasStrength"],
    [50739, "ShadowScale"],
    [50740, "DNGPrivateData"],
    [50741, "MakerNoteSafety"],
    [50778, "CalibrationIlluminant1"],
    [50779, "CalibrationIlluminant2"],
    [50780, "BestQualityScale"],
    [50827, "ActiveArea"],
    [50828, "MaskedAreas"],
    [50829, "AsShotICCProfile"],
    [50830, "AsShotPreProfileMatrix"],
    [50831, "CurrentICCProfile"],
    [50832, "CurrentPreProfileMatrix"],
    [50932, "CameraCalibrationSignature"],
    [50933, "ProfileCalibrationSignature"],
    [50934, "AsShotProfileName"],
    [50935, "NoiseReductionApplied"],
    [50936, "ProfileName"],
    [50937, "ProfileHueSatMapDims"],
    [50938, "ProfileHueSatMapData1"],
    [50939, "ProfileHueSatMapData2"],
    [50940, "ProfileToneCurve"],
    [50941, "ProfileEmbedPolicy"],
    [50942, "ProfileCopyright"],
    [50964, "ForwardMatrix1"],
    [50965, "ForwardMatrix2"],
    [50966, "PreviewApplicationName"],
    [50967, "PreviewApplicationVersion"],
    [50968, "PreviewSettingsName"],
    [50969, "PreviewSettingsDigest"],
    [50970, "PreviewColorSpace"],
    [50971, "PreviewDateTime"],
    [50972, "RawImageDigest"],
    [50973, "OriginalRawFileDigest"],
    [50974, "SubTileBlockSize"],
    [50975, "RowInterleaveFactor"],
    [50981, "ProfileLookTableDims"],
    [50982, "ProfileLookTableData"],
    [51107, "ProfileHueSatMapEncoding"],
    [51108, "ProfileLookTableEncoding"],
    [51109, "BaselineExposureOffset"],
    [51110, "DefaultBlackRender"],
    [51125, "DefaultUserCrop"],
    [52529, "CalibrationIlluminant3"],
    [52530, "ColorMatrix3"],
    [52531, "CameraCalibration3"],
    [52525, "ProfileGainTableMap"],
    [52532, "ForwardMatrix3"],
    [52533, "ProfileHueSatMapData3"],
    [52534, "IlluminantData1"],
    [52535, "IlluminantData2"],
    [52536, "IlluminantData3"],
    [52544, "ProfileGainTableMap2"],
]);

export const EXACT_TAGS = new Map([
    ["analogbalance", { strategy: STRATEGY.CHANNEL_RATIO }],
    ["antialiasstrength", { strategy: STRATEGY.POSITIVE_RATIO }],
    ["asshotneutral", { strategy: STRATEGY.CHANNEL_RATIO }],
    ["asshotwhitexy", { strategy: STRATEGY.WHITE_POINT_XY }],
    ["baselineexposure", { strategy: STRATEGY.ADDITIVE }],
    ["baselineexposureoffset", { strategy: STRATEGY.ADDITIVE }],
    ["baselinenoise", { strategy: STRATEGY.POSITIVE_RATIO }],
    ["baselinesharpness", { strategy: STRATEGY.POSITIVE_RATIO }],
    ["bayergreensplit", { strategy: STRATEGY.ADDITIVE }],
    ["blacklevel", { strategy: STRATEGY.ADDITIVE }],
    ["blackleveldeltah", { strategy: STRATEGY.ADDITIVE }],
    ["blackleveldeltav", { strategy: STRATEGY.ADDITIVE }],
    ["chromablurradius", { strategy: STRATEGY.POSITIVE_RATIO }],
    ["defaultblackrender", { strategy: STRATEGY.COPY_STYLE }],
    ["linearizationtable", { strategy: STRATEGY.MONOTONIC_LUT }],
    ["linearresponselimit", { strategy: STRATEGY.POSITIVE_RATIO }],
    ["profilegaintablemap", { strategy: STRATEGY.GAIN_MAP }],
    ["profilegaintablemap2", { strategy: STRATEGY.GAIN_MAP }],
    ["profilehuesatmapdata1", { strategy: STRATEGY.HSV_TABLE, dimsKey: "profilehuesatmapdims", encodingKey: "profilehuesatmapencoding" }],
    ["profilehuesatmapdata2", { strategy: STRATEGY.HSV_TABLE, dimsKey: "profilehuesatmapdims", encodingKey: "profilehuesatmapencoding" }],
    ["profilehuesatmapencoding", { strategy: STRATEGY.COPY_STYLE }],
    ["profilelooktabledata", { strategy: STRATEGY.HSV_TABLE, dimsKey: "profilelooktabledims", encodingKey: "profilelooktableencoding" }],
    ["profilelooktableencoding", { strategy: STRATEGY.COPY_STYLE }],
    ["profiletonecurve", { strategy: STRATEGY.TONE_CURVE }],
    ["shadowscale", { strategy: STRATEGY.POSITIVE_RATIO }],
    ["whitelevel", { strategy: STRATEGY.ADDITIVE }],
]);

export const MATRIX_PREFIXES = [
    "cameracalibration",
    "colormatrix",
    "currentpreprofilematrix",
    "forwardmatrix",
    "reductionmatrix",
    "asshotpreprofilematrix",
];

export const METADATA_PREFIXES = [
    "activearea",
    "asshotprofilename",
    "bestqualityscale",
    "blacklevelrepeatdim",
    "calibrationilluminant",
    "cameracalibrationsignature",
    "cameramodel",
    "cameraserialnumber",
    "cfalayout",
    "cfaplanecolor",
    "colorimetricreference",
    "copyright",
    "datetime",
    "defaultcrop",
    "defaultscale",
    "digest",
    "dngbackwardversion",
    "dngversion",
    "exif",
    "extracameraprofiles",
    "filename",
    "groupname",
    "lensinfo",
    "localizedcamera",
    "makernotesafety",
    "maskedareas",
    "name",
    "noisereductionapplied",
    "originalraw",
    "preview",
    "private",
    "profilecalibrationsignature",
    "profilecopyright",
    "profileembedpolicy",
    "profilehuesatmapdims",
    "profilelooktabledims",
    "rawdatauniqueid",
    "rawimagedigest",
    "semantic",
    "serial",
    "signature",
    "subtileblocksize",
    "uniquecamera",
    "version",
];

export function tagNameFromId(tagId) {
    return TAG_NAME_BY_ID.get(tagId) || `Tag${tagId}`;
}

export function resolveTagSchema(normalizedKey) {
    if (EXACT_TAGS.has(normalizedKey)) {
        return EXACT_TAGS.get(normalizedKey);
    }

    if (MATRIX_PREFIXES.some((prefix) => normalizedKey.startsWith(prefix))) {
        return { strategy: STRATEGY.MATRIX };
    }

    return null;
}

export function isMetadataKey(normalizedKey) {
    return METADATA_PREFIXES.some((prefix) => normalizedKey.startsWith(prefix));
}
